"""add candidates, candidate_documents, canonical_documents

Revision ID: 6ced76376cee
Revises: 50dc371b2ad2
Create Date: 2026-08-18 21:06:08.857052

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6ced76376cee'
down_revision: str | Sequence[str] | None = '50dc371b2ad2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_tenant_id'), 'candidates', ['tenant_id'], unique=False)
    op.create_table('candidate_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('document_status', sa.String(length=32), nullable=False),
    sa.Column('parser_status', sa.String(length=32), nullable=False),
    sa.Column('parser_name', sa.String(length=128), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('parse_error_code', sa.String(length=64), nullable=True),
    sa.Column('parse_error_message', sa.String(length=500), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_candidate_documents_candidate_id'), 'candidate_documents', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_sha256_hash'), 'candidate_documents', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_candidate_documents_tenant_id'), 'candidate_documents', ['tenant_id'], unique=False)
    op.create_table('canonical_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_document_id', sa.Uuid(), nullable=False),
    sa.Column('parser_name', sa.String(length=128), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_document_id'], ['candidate_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_documents_candidate_document_id'), 'canonical_documents', ['candidate_document_id'], unique=False)
    op.create_index(op.f('ix_canonical_documents_tenant_id'), 'canonical_documents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonical_documents_tenant_id'), table_name='canonical_documents')
    op.drop_index(op.f('ix_canonical_documents_candidate_document_id'), table_name='canonical_documents')
    op.drop_table('canonical_documents')
    op.drop_index(op.f('ix_candidate_documents_tenant_id'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_sha256_hash'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_candidate_id'), table_name='candidate_documents')
    op.drop_table('candidate_documents')
    op.drop_index(op.f('ix_candidates_tenant_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
