"""add candidate_profile_versions

Revision ID: e631b45159cd
Revises: 6ced76376cee
Create Date: 2026-08-18 21:36:06.174257

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e631b45159cd'
down_revision: str | Sequence[str] | None = '6ced76376cee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profile_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_document_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_document_id', sa.Uuid(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('model_provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('profile_content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_document_id'], ['candidate_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['canonical_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'version_number', name='uq_candidate_profile_version')
    )
    op.create_index(op.f('ix_candidate_profile_versions_candidate_id'), 'candidate_profile_versions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_profile_versions_tenant_id'), 'candidate_profile_versions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_profile_versions_tenant_id'), table_name='candidate_profile_versions')
    op.drop_index(op.f('ix_candidate_profile_versions_candidate_id'), table_name='candidate_profile_versions')
    op.drop_table('candidate_profile_versions')
    # ### end Alembic commands ###
