import os
import uuid
from pathlib import Path


class LocalFilesystemStorage:
    """MVP DocumentStorage implementation on local disk.

    Encryption-at-rest: this implementation relies on host/disk-level
    protections (e.g. full-disk encryption), NOT application-level
    encryption. See docs/SECURITY_PRIVACY.md — production deployments
    handling real candidate data must swap in an encrypted/object-storage
    backend behind this same DocumentStorage interface before go-live.

    Path-traversal safety: storage_key is always generated by this class
    from a UUID, never derived from a client-supplied filename, so there
    is no user-controlled path segment to traverse with.
    """

    def __init__(self, root: str) -> None:
        self._root = Path(root)

    def _path_for(self, storage_key: str) -> Path:
        return self._root / storage_key

    async def save(self, *, tenant_id: uuid.UUID, content: bytes) -> str:
        storage_key = f"{tenant_id}/{uuid.uuid4().hex}"
        path = self._path_for(storage_key)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = path.with_name(f"{path.name}.{uuid.uuid4().hex}.tmp")
        tmp_path.write_bytes(content)
        os.replace(tmp_path, path)  # atomic on the same filesystem
        return storage_key

    async def read(self, *, storage_key: str) -> bytes:
        return self._path_for(storage_key).read_bytes()

    async def delete(self, *, storage_key: str) -> None:
        self._path_for(storage_key).unlink(missing_ok=True)
